### PR TITLE
#38 add metadata

### PR DESCRIPTION
**Pull request by funkydunc**
https://github.com/iiif-prezi/iiif-prezi3/issues/38

AddMetadata class with tests

### CODE REVIEW

**Comment by digitaldogsbody** [comment]
@funkydunc Can you rebase against main now that #63 is merged? That should hopefully fix the failing tests.

**Comment by digitaldogsbody** [comment]
I don't know why the linter is failing only for one Python version :confused:

Given that the tests pass for the others, I don't see this as a block to merge, but it would be nice to work out why!

**Comment by azaroth42** [comment]
What happens if the function is passed a dict or langstring instance, per Glen's [comment](https://github.com/iiif-prezi/iiif-prezi3/issues/38#issuecomment-1126066499)?

**Comment by funkydunc** [comment]
> What happens if the function is passed a dict or langstring instance, per Glen's [comment](https://github.com/iiif-prezi/iiif-prezi3/issues/38#issuecomment-1126066499)?

@azaroth42 @glenrobson how would you like the function to accept args as different datatypes? Would something like this, using additional keyword arguments on the method be ok?

```
    def add_metadata(self, label, value, metadata_dict=None, langstring=None):
        #check the presence of the above arguments (and they are valid) before adding them to the metadata
```

**Comment by glenrobson** [comment]
I'd lean more on others (cc @azaroth42 @digitaldogsbody @giacomomarchioro) on if this is the python way of doing things but could you check the type to see if its String, dict or LngString?

**Comment by azaroth42** [comment]
+1 to testing the type of the argument. if type(label) == dict: # do dict stuff

**Comment by digitaldogsbody** [comment]
I would say raise `TypeError` if the value is not one of the correct types

**Comment by glenrobson** [comment]
We need to re-run the tests to see why it failed. 

Mike to change workflow on: target - forces workflow to run from main rather than remote target.

**Pull request merged**
