### PR TITLE
Add 0118-multivalue recipe

### PR DESCRIPTION
**Pull request by giacomomarchioro**

### CODE REVIEW

**Comment by glenrobson** [comment]
Rename `docs/recipes/scripts/0118-multivalue.py` to `docs/recipes/scripts/0118-multivalue-method1.py`

**Comment by glenrobson** [comment]
Recipe uses a straight jpg image rather than a IIIF image so would need to add the image manually until this helper is written: https://github.com/iiif-prezi/iiif-prezi3/issues/132

**Comment by glenrobson** [comment]
To test locally:
```
python test_cookbook.py ../docs/recipes/0001-mvm-image.md
```

**Comment by digitaldogsbody** [comment]
> To test locally:
> 
> ```
> python test_cookbook.py ../docs/recipes/0001-mvm-image.md
> ```

NB this needs to be run from within the `utils` directory

**Pull request merged**
