### PR TITLE
Autofix linting issues

### PR DESCRIPTION
**Pull request by helrond**
Adds `isort` and `autopep8` to try and autofix linting problems before running `flake8`. This resulted in some linting changes to a few files.

`autopep8` comes with an `aggressive` flag that can be passed in multiple times. The more it's passed in the more aggressive the library will be about fixing issues. I've left it fairly lax for the purposes of a less invasive PR but that could be changed pretty easily.

I've also added those additional libraries used in `tox` into `setup.py`. Curious if this resolves the issue you encountered @digitaldogsbody?

### CODE REVIEW

**Review by azaroth42 — APPROVED** [review]

**Comment by digitaldogsbody** [comment]
Is there a way we can adjust or ignore the setting that is splitting lines? My personal feeling is that this actually makes the code harder to read.

e.g changes such as the one from
```python
extension_file = os.path.join(os.path.dirname(__file__), 'config', 'extensions.json')
```
to
```python
extension_file = os.path.join(os.path.dirname(
     __file__), 'config', 'extensions.json')
```

We already decided that we didn't want to force a split at 80 characters, and so E501 (line length) is set to ignore in the config, which makes it feel counter-intuitive (to me anyway) that the above example should get split when lines such as that below are ok

```python
return json.dumps({"@context": "http://iiif.io/api/presentation/3/context.json", **self.dict(exclude_unset=True, exclude_none=True, **dict_kwargs)}, **json_kwargs)
```

**Comment by helrond** [comment]
Yup - I've ignored E501 in `autopep8` and it seems to have the desired result...

**Comment by digitaldogsbody** [comment]
Great, thanks! My other question was about the development dependencies - my understanding of `setup_requires` was that it was for tools needed during the build process, and that packages listed there didn't get installed when you installed the package itself.

I am wary of moving tox etc to `install_requires`, since they aren't needed to actually use the library as an end-user. For people who want to clone the repo and do development it also seems likely to me that they won't be installing the library via the setuptools / setup.py method anyway.

Perhaps we could move them to a `requirements.dev.txt` file so they can be manually installed using pip etc as and when required. What do people think?

**Comment by helrond** [comment]
OK that's taken care of as well. I should note, however, that if you're just using `tox` to run tests and linting, you don't need to install all these other dependencies because tox will take care of that for you. It's only if you're trying to run linting or something outside of tox that you'll need to install all these other libraries.

**Comment by azaroth42** [comment]
Merging in advance of hackathon.

**Pull request merged**
